version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
      - pip install pytest pytest-flask  # Para las pruebas

  pre_build:
    commands:
      - echo "Ejecutando pruebas unitarias..."
      - python -m pytest -v -s tests/

  build:
    commands:
      - echo "Empaquetando aplicación..."
      - zip -r blacklist-app.zip . -x "*.git*" "*__pycache__*" "*.pyc" ".env*" "postman/*" "tests/*" "migrations/*"

artifacts:
  files:
    - blacklist-app.zip
  discard-paths: no